### ISSUE TITLE
Great and thanks! But why isn't this official and on xbmc.org?

### ISSUE THREAD

**Issue by piejanssens** [cflannagan/service.subtitles.addic7ed#11]
Just wondering..

**Comment by piejanssens** [comment]
I don't know if it's you, but I found this http://be4i.blogspot.be/2013/05/addic7ed-service-for-xbmc-subtitles.html

So addic7ed asked to be removed from xbmc's official repo.

**Comment by cflannagan** [comment]
Hi @piejanssens !

You answered your own question ;) addic7ed asked to be removed from XBMC's official repo a long time ago. Since 2011 in fact. See here: http://forum.xbmc.org/showthread.php?tid=159426
