### ISSUE TITLE
Requirement: beautifulsoup

### ISSUE THREAD

**Issue by fifteenblade** [cflannagan/service.subtitles.addic7ed#12]
Hi,

Please update the Readme:
script.module.beautifulsoup is required - on a naked xbmc installation it's not there.
Just install "The Big Pictures Screensaver" then beautifulsoup is automatically installed.
thx

**Comment by cflannagan** [comment]
Should be fixed with this PR https://github.com/cflannagan/service.subtitles.addic7ed/pull/19 - let me know if issue persists
