### ISSUE TITLE
Other language ?

### ISSUE THREAD

**Issue by benjbubu** [cflannagan/service.subtitles.addic7ed#17]
Hi,

Your plugin is working. Just a question : i have only results in english. Is it possible to set another language ?

**Comment by fndmossmann** [comment]
The script search subtitles according to the languages you've chosen on XBMC subtitle settings.
To change it, go to Settings -> Video -> Subtitles -> Languages to Download Subtitles For, the choose the languages you want.
On your setup, probably have only English subtitles are enabled.
You can enable more then one language.
