### ISSUE TITLE
Readme update my fork

### ISSUE THREAD

**Issue by Amelandbor** [cflannagan/service.subtitles.addic7ed#20]
You can update the readme to include my fork, as I will be maintaining mine and solving issues in the future.

**Comment by cflannagan** [comment]
Thanks for stepping up, @Amelandbor - I've updated README.md to point to your fork. 

Also, if you haven't already, there might be a couple of pull requests from others that I pretty recently merged in (last couple of days) that should go into your fork - some of those actually solved issues I were experiencing (thanks to them!)
