### ISSUE TITLE
Multiple subs for a release

### ISSUE THREAD

**Issue by odon** [cflannagan/service.subtitles.addic7ed#6]
Hi,
on addic7ed, it may have multiple subtitles under the same release (ie, same "NewsTitle"). It seems the addon can only returns the first sub of a release. Therefore, some languages which are provided as other sub of a release cannot been found.

sample: www.addic7ed.com/serie/Suburgatory/2/8/addic7ed for release LOL with English, French and Greek.

If both English and French are selected in XBMC, only English is available in the addon.
If only French is selected, no subs is available in the addon.

**Comment by cflannagan** [comment]
Will take a look, thanks for supplying an example

**Comment by odon** [comment]
Thank you,
seems service shall loop for every for all "langs_html = subs.findNext("td", {"class" : "language"})" within a "for subs in soup("td", {"class":"NewsTitle", "colspan" : "3"}):" loop, but i definitely lack Python knowledge myself...

**Comment by thombet** [comment]
I offer a solution for this bug.
See pull #16

**Comment by cflannagan** [comment]
Thanks @TomSpyCell ! It've been merged, and did resolve the issue for me as well post-Helix. 

A side comment - let me know if you are interested in maintaining this project.

**Comment by thombet** [comment]
Thanks for the offer @cflannagan! Even if I am not a python expert, I'll be glad to contribute to this project.
