### ISSUE TITLE
'userdata/addon_data/script.xbmc.subtitles/settings.xml' does not exist

### ISSUE THREAD

**Issue by thelightning87** [cflannagan/service.subtitles.addic7ed#8]
Running XBMC 13.1.
'userdata/addon_data/script.xbmc.subtitles/settings.xml' file does not exist. 

Other subtitle plugins have thier own config file, for example service.subtitles.opensubtitles and service.subtitles.podnapisi

**Comment by cflannagan** [comment]
Your issue doesn't appear to be for the service.subtitles.addic7ed (your error message is referring to script.xbmc.subtitles, and this is the service.subtitles.addic7ed project). 

Furthermore, in my personal XBMC installation,  service.subtitles.opensubtitles does not have a settings.xml, but rather, addon.xml. Just like service.subtitles.addic7ed. See here: 

https://github.com/amet/service.subtitles.opensubtitles/blob/Gotham/service.subtitles.opensubtitles/addon.xml

and

https://github.com/amet/service.subtitles.podnapisi/blob/Gotham/service.subtitles.podnapisi/addon.xml
