### ISSUE TITLE
Script fails due to missing BeautifulSoup module

### ISSUE THREAD

**Issue by danielkza** [cflannagan/service.subtitles.addic7ed#9]
As per title, the module doesn't exist in my installation (XBMC 13.1).

**Comment by cflannagan** [comment]
@danielkza any ideas how your script.module.beautifulsoup went missing? I have that in my XBMC installation and I don't recall adding that when doing a fresh installation of Gotham. 

Going to try a few things here

**Comment by cflannagan** [comment]
I haven't had any luck. Any more details you can share regarding this issue? Have you managed to get this resolved yet?

**Comment by cflannagan** [comment]
I suspect this PR would resolve your issue - let me know if it doesn't

https://github.com/cflannagan/service.subtitles.addic7ed/pull/19
